import { forwardRef, useId, type SVGProps } from "react";
// Generated by scripts/icons/build.py. Edit the geometry source.
type IconProps = SVGProps<SVGSVGElement> & { weight?: string; size?: number | string };
export const FolderClosedIcon = forwardRef<SVGSVGElement, IconProps>(function FolderClosedIcon(props, ref) {
  const { weight: _weight, size = 24, ...rest } = props;

  return <svg ref={ref} width={size} height={size} aria-hidden="true" viewBox="0 0 24 24" fill="none" stroke="currentColor" {...rest} strokeWidth={1.75} strokeLinecap="round" strokeLinejoin="round" data-backchat-icon="folder-closed"><path d="M3 8V6a2 2 0 0 1 2-2h4l2 2h8a2 2 0 0 1 2 2v10a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V8Zm0 1h18"/></svg>;
});
export const FolderOpenIcon = forwardRef<SVGSVGElement, IconProps>(function FolderOpenIcon(props, ref) {
  const { weight: _weight, size = 24, ...rest } = props;

  return <svg ref={ref} width={size} height={size} aria-hidden="true" viewBox="0 0 24 24" fill="none" stroke="currentColor" {...rest} strokeWidth={1.75} strokeLinecap="round" strokeLinejoin="round" data-backchat-icon="folder-open"><path d="M5 20H19C20.10457 20 21.17909 19.10457 21.4 18L22.6 12C22.82091 10.89543 22.10457 10 21 10V8a2 2 0 0 0-2-2h-8L9 4H5a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2Z"/><path d="M5 20C3.89543 20 3.17909 19.10457 3.4 18L4.6 12C4.82091 10.89543 5.89543 10 7 10H21"/></svg>;
});
export const ComposeIcon = forwardRef<SVGSVGElement, IconProps>(function ComposeIcon(props, ref) {
  const { weight: _weight, size = 24, ...rest } = props;

  return <svg ref={ref} width={size} height={size} aria-hidden="true" viewBox="0 0 24 24" fill="none" stroke="currentColor" {...rest} strokeWidth={1.75} strokeLinecap="round" strokeLinejoin="round" data-backchat-icon="compose"><path d="M10 4H6a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2v-4"/><path d="m10 11 8-8a1.4142135624 1.4142135624 0 0 1 2 2l-8 8-3 1 1-3Z"/></svg>;
});
export const SearchIcon = forwardRef<SVGSVGElement, IconProps>(function SearchIcon(props, ref) {
  const { weight: _weight, size = 24, ...rest } = props;

  return <svg ref={ref} width={size} height={size} aria-hidden="true" viewBox="0 0 24 24" fill="none" stroke="currentColor" {...rest} strokeWidth={1.75} strokeLinecap="round" strokeLinejoin="round" data-backchat-icon="search"><circle cx="10.5" cy="10.5" r="6.5"/><path d="M15.0962 15.0962 L20 20"/></svg>;
});
export const ChatIcon = forwardRef<SVGSVGElement, IconProps>(function ChatIcon(props, ref) {
  const { weight: _weight, size = 24, ...rest } = props;

  return <svg ref={ref} width={size} height={size} aria-hidden="true" viewBox="0 0 24 24" fill="none" stroke="currentColor" {...rest} strokeWidth={1.75} strokeLinecap="round" strokeLinejoin="round" data-backchat-icon="chat"><path d="M6 4h12a3 3 0 0 1 3 3v8a3 3 0 0 1-3 3h-8l-4 2v-2a3 3 0 0 1-3-3V7a3 3 0 0 1 3-3Z"/></svg>;
});
export const CoordinationIcon = forwardRef<SVGSVGElement, IconProps>(function CoordinationIcon(props, ref) {
  const { weight: _weight, size = 24, ...rest } = props;

  return <svg ref={ref} width={size} height={size} aria-hidden="true" viewBox="0 0 24 24" fill="none" stroke="currentColor" {...rest} strokeWidth={1.75} strokeLinecap="round" strokeLinejoin="round" data-backchat-icon="coordination"><circle cx="12" cy="5" r="2"/><circle cx="5" cy="19" r="2"/><circle cx="19" cy="19" r="2"/><path d="M12 7v5M5 17v-3a2 2 0 0 1 2-2h10a2 2 0 0 1 2 2v3"/></svg>;
});
export const ProjectsIcon = forwardRef<SVGSVGElement, IconProps>(function ProjectsIcon(props, ref) {
  const { weight: _weight, size = 24, ...rest } = props;

  return <svg ref={ref} width={size} height={size} aria-hidden="true" viewBox="0 0 24 24" fill="none" stroke="currentColor" {...rest} strokeWidth={1.75} strokeLinecap="round" strokeLinejoin="round" data-backchat-icon="projects"><path d="M12.0000 3.5000 L19.3612 7.7500 L19.3612 16.2500 L12.0000 20.5000 L4.6388 16.2500 L4.6388 7.7500Z"/><path d="M4.6388 7.7500 L12 12 L19.3612 7.7500 M12 12V20.5"/></svg>;
});
export const BranchIcon = forwardRef<SVGSVGElement, IconProps>(function BranchIcon(props, ref) {
  const { weight: _weight, size = 24, ...rest } = props;

  return <svg ref={ref} width={size} height={size} aria-hidden="true" viewBox="0 0 24 24" fill="none" stroke="currentColor" {...rest} strokeWidth={1.75} strokeLinecap="round" strokeLinejoin="round" data-backchat-icon="branch"><circle cx="6" cy="5" r="2"/><circle cx="6" cy="19" r="2"/><circle cx="18" cy="7" r="2"/><path d="M6 7v10M6 15h6a6 6 0 0 0 6-6"/></svg>;
});
export const ChatsIcon = forwardRef<SVGSVGElement, IconProps>(function ChatsIcon(props, ref) {
  const { weight: _weight, size = 24, ...rest } = props;

  return <svg ref={ref} width={size} height={size} aria-hidden="true" viewBox="0 0 24 24" fill="none" stroke="currentColor" {...rest} strokeWidth={1.75} strokeLinecap="round" strokeLinejoin="round" data-backchat-icon="chats"><path d="M13 4H5a2 2 0 0 0-2 2v7a2 2 0 0 0 2 2v3l3-3M10 8h9a2 2 0 0 1 2 2v6a2 2 0 0 1-2 2v3l-4-3h-5a2 2 0 0 1-2-2v-6a2 2 0 0 1 2-2Z"/></svg>;
});
export const ParticipantsIcon = forwardRef<SVGSVGElement, IconProps>(function ParticipantsIcon(props, ref) {
  const { weight: _weight, size = 24, ...rest } = props;

  return <svg ref={ref} width={size} height={size} aria-hidden="true" viewBox="0 0 24 24" fill="none" stroke="currentColor" {...rest} strokeWidth={1.75} strokeLinecap="round" strokeLinejoin="round" data-backchat-icon="participants"><circle cx="8" cy="8" r="3"/><path d="M3 21v-1a5 5 0 0 1 10 0v1M16 6a3 3 0 0 1 0 6M17 16a4 4 0 0 1 4 4v1"/></svg>;
});
export const ScheduleIcon = forwardRef<SVGSVGElement, IconProps>(function ScheduleIcon(props, ref) {
  const { weight: _weight, size = 24, ...rest } = props;

  return <svg ref={ref} width={size} height={size} aria-hidden="true" viewBox="0 0 24 24" fill="none" stroke="currentColor" {...rest} strokeWidth={1.75} strokeLinecap="round" strokeLinejoin="round" data-backchat-icon="schedule"><path d="M9 20H6a3 3 0 0 1-3-3V6a3 3 0 0 1 3-3h11a3 3 0 0 1 3 3v3M3 8h17"/><path d="M19.3284 19.8284a4 4 0 1 1 0-5.6568L21 15.5M21 12.5v3h-3"/></svg>;
});
export const SettingsIcon = forwardRef<SVGSVGElement, IconProps>(function SettingsIcon(props, ref) {
  const { weight: _weight, size = 24, ...rest } = props;

  return <svg ref={ref} width={size} height={size} aria-hidden="true" viewBox="0 0 24 24" fill="none" stroke="currentColor" {...rest} strokeWidth={1.75} strokeLinecap="round" strokeLinejoin="round" data-backchat-icon="settings"><path d="M3 7h4m4 0h10M3 17h10m4 0h4"/><circle cx="9" cy="7" r="2"/><circle cx="15" cy="17" r="2"/></svg>;
});
export const StarIcon = forwardRef<SVGSVGElement, IconProps>(function StarIcon(props, ref) {
  const { weight: _weight, size = 24, ...rest } = props;

  return <svg ref={ref} width={size} height={size} aria-hidden="true" viewBox="0 0 24 24" fill="none" stroke="currentColor" {...rest} strokeWidth={1.75} strokeLinecap="round" strokeLinejoin="round" data-backchat-icon="star"><path d="m12 3 2.8 5.7 6.2.9-4.5 4.4 1.1 6.2-5.6-3-5.6 3 1.1-6.2L3 9.6l6.2-.9L12 3Z"/></svg>;
});
export const StarFilledIcon = forwardRef<SVGSVGElement, IconProps>(function StarFilledIcon(props, ref) {
  const { weight: _weight, size = 24, ...rest } = props;

  return <svg ref={ref} width={size} height={size} aria-hidden="true" viewBox="0 0 24 24" fill="none" stroke="currentColor" {...rest} strokeWidth={1.75} strokeLinecap="round" strokeLinejoin="round" data-backchat-icon="star-filled"><path d="m12 3 2.8 5.7 6.2.9-4.5 4.4 1.1 6.2-5.6-3-5.6 3 1.1-6.2L3 9.6l6.2-.9L12 3Z" fill="currentColor"/></svg>;
});
export const BellIcon = forwardRef<SVGSVGElement, IconProps>(function BellIcon(props, ref) {
  const { weight: _weight, size = 24, ...rest } = props;

  return <svg ref={ref} width={size} height={size} aria-hidden="true" viewBox="0 0 24 24" fill="none" stroke="currentColor" {...rest} strokeWidth={1.75} strokeLinecap="round" strokeLinejoin="round" data-backchat-icon="bell"><path d="M5 17c2-2 2-4 2-7a5 5 0 0 1 10 0c0 3 0 5 2 7H5ZM10 21h4"/></svg>;
});
export const BellMutedIcon = forwardRef<SVGSVGElement, IconProps>(function BellMutedIcon(props, ref) {
  const { weight: _weight, size = 24, ...rest } = props;

  return <svg ref={ref} width={size} height={size} aria-hidden="true" viewBox="0 0 24 24" fill="none" stroke="currentColor" {...rest} strokeWidth={1.75} strokeLinecap="round" strokeLinejoin="round" data-backchat-icon="bell-muted"><path d="M10 5.4A5 5 0 0 1 17 10v1M7 9v1c0 3 0 5-2 7h9M10 21h4M3 3l18 18"/></svg>;
});
export const PinIcon = forwardRef<SVGSVGElement, IconProps>(function PinIcon(props, ref) {
  const { weight: _weight, size = 24, ...rest } = props;

  return <svg ref={ref} width={size} height={size} aria-hidden="true" viewBox="0 0 24 24" fill="none" stroke="currentColor" {...rest} strokeWidth={1.75} strokeLinecap="round" strokeLinejoin="round" data-backchat-icon="pin"><path d="m14 3 7 7-3 1-4 4v3L6 10h3l4-4 1-3ZM10 14l-7 7"/></svg>;
});
export const PinOffIcon = forwardRef<SVGSVGElement, IconProps>(function PinOffIcon(props, ref) {
  const { weight: _weight, size = 24, ...rest } = props;
  const cut = useId();
  return <svg ref={ref} width={size} height={size} aria-hidden="true" viewBox="0 0 24 24" fill="none" stroke="currentColor" {...rest} strokeWidth={1.75} strokeLinecap="round" strokeLinejoin="round" data-backchat-icon="pin-off"><defs><mask id={cut}><rect width="24" height="24" fill="white" stroke="none"/><path d="M3 3 21 21" stroke="black" strokeWidth="4"/></mask></defs><g mask={"url(#" + cut + ")"}><path d="m14 3 7 7-3 1-4 4v3L6 10h3l4-4 1-3ZM10 14l-7 7"/></g><path d="M3 3l18 18"/></svg>;
});
export const ArchiveIcon = forwardRef<SVGSVGElement, IconProps>(function ArchiveIcon(props, ref) {
  const { weight: _weight, size = 24, ...rest } = props;

  return <svg ref={ref} width={size} height={size} aria-hidden="true" viewBox="0 0 24 24" fill="none" stroke="currentColor" {...rest} strokeWidth={1.75} strokeLinecap="round" strokeLinejoin="round" data-backchat-icon="archive"><rect x="3" y="4" width="18" height="4" rx="1"/><path d="M5 11v8a2 2 0 0 0 2 2h10a2 2 0 0 0 2-2v-8M9 12h6"/></svg>;
});
export const TrashIcon = forwardRef<SVGSVGElement, IconProps>(function TrashIcon(props, ref) {
  const { weight: _weight, size = 24, ...rest } = props;

  return <svg ref={ref} width={size} height={size} aria-hidden="true" viewBox="0 0 24 24" fill="none" stroke="currentColor" {...rest} strokeWidth={1.75} strokeLinecap="round" strokeLinejoin="round" data-backchat-icon="trash"><path d="M4 6h16M9 6V3h6v3M6 9l1 12h10l1-12M12 10v7"/></svg>;
});
export const PaletteIcon = forwardRef<SVGSVGElement, IconProps>(function PaletteIcon(props, ref) {
  const { weight: _weight, size = 24, ...rest } = props;

  return <svg ref={ref} width={size} height={size} aria-hidden="true" viewBox="0 0 24 24" fill="none" stroke="currentColor" {...rest} strokeWidth={1.75} strokeLinecap="round" strokeLinejoin="round" data-backchat-icon="palette"><path d="M21 12a9 9 0 1 0-9 9h1a2 2 0 0 0 1.5-3.3 2 2 0 0 1 1.5-3.2H18a3 3 0 0 0 3-2.5Z"/><circle cx="8" cy="8" r="1.25" fill="currentColor" stroke="none"/><circle cx="13" cy="6.5" r="1.25" fill="currentColor" stroke="none"/><circle cx="6.5" cy="13" r="1.25" fill="currentColor" stroke="none"/></svg>;
});
export const PlusIcon = forwardRef<SVGSVGElement, IconProps>(function PlusIcon(props, ref) {
  const { weight: _weight, size = 24, ...rest } = props;

  return <svg ref={ref} width={size} height={size} aria-hidden="true" viewBox="0 0 24 24" fill="none" stroke="currentColor" {...rest} strokeWidth={1.75} strokeLinecap="round" strokeLinejoin="round" data-backchat-icon="plus"><path d="M12 5v14M5 12h14"/></svg>;
});
export const ChevronRightIcon = forwardRef<SVGSVGElement, IconProps>(function ChevronRightIcon(props, ref) {
  const { weight: _weight, size = 24, ...rest } = props;

  return <svg ref={ref} width={size} height={size} aria-hidden="true" viewBox="0 0 24 24" fill="none" stroke="currentColor" {...rest} strokeWidth={1.75} strokeLinecap="round" strokeLinejoin="round" data-backchat-icon="chevron-right"><path d="m9 6 6 6-6 6"/></svg>;
});
export const ChevronDownIcon = forwardRef<SVGSVGElement, IconProps>(function ChevronDownIcon(props, ref) {
  const { weight: _weight, size = 24, ...rest } = props;

  return <svg ref={ref} width={size} height={size} aria-hidden="true" viewBox="0 0 24 24" fill="none" stroke="currentColor" {...rest} strokeWidth={1.75} strokeLinecap="round" strokeLinejoin="round" data-backchat-icon="chevron-down"><path d="m6 9 6 6 6-6"/></svg>;
});
export const MoreIcon = forwardRef<SVGSVGElement, IconProps>(function MoreIcon(props, ref) {
  const { weight: _weight, size = 24, ...rest } = props;

  return <svg ref={ref} width={size} height={size} aria-hidden="true" viewBox="0 0 24 24" fill="none" stroke="currentColor" {...rest} strokeWidth={1.75} strokeLinecap="round" strokeLinejoin="round" data-backchat-icon="more"><circle cx="5" cy="12" r="1.25" fill="currentColor" stroke="none"/><circle cx="12" cy="12" r="1.25" fill="currentColor" stroke="none"/><circle cx="19" cy="12" r="1.25" fill="currentColor" stroke="none"/></svg>;
});
export const CheckIcon = forwardRef<SVGSVGElement, IconProps>(function CheckIcon(props, ref) {
  const { weight: _weight, size = 24, ...rest } = props;

  return <svg ref={ref} width={size} height={size} aria-hidden="true" viewBox="0 0 24 24" fill="none" stroke="currentColor" {...rest} strokeWidth={1.75} strokeLinecap="round" strokeLinejoin="round" data-backchat-icon="check"><path d="m5 12 4 4L19 6"/></svg>;
});
export const TerminalIcon = forwardRef<SVGSVGElement, IconProps>(function TerminalIcon(props, ref) {
  const { weight: _weight, size = 24, ...rest } = props;

  return <svg ref={ref} width={size} height={size} aria-hidden="true" viewBox="0 0 24 24" fill="none" stroke="currentColor" {...rest} strokeWidth={1.75} strokeLinecap="round" strokeLinejoin="round" data-backchat-icon="terminal"><rect x="3" y="4" width="18" height="16" rx="2"/><path d="m7 9 3 3-3 3M13 16h4"/></svg>;
});
export const DatabaseIcon = forwardRef<SVGSVGElement, IconProps>(function DatabaseIcon(props, ref) {
  const { weight: _weight, size = 24, ...rest } = props;

  return <svg ref={ref} width={size} height={size} aria-hidden="true" viewBox="0 0 24 24" fill="none" stroke="currentColor" {...rest} strokeWidth={1.75} strokeLinecap="round" strokeLinejoin="round" data-backchat-icon="database"><ellipse cx="12" cy="6" rx="8" ry="3"/><path d="M4 6v12a8 3 0 0 0 16 0V6M4 12a8 3 0 0 0 16 0"/></svg>;
});
export const PluginIcon = forwardRef<SVGSVGElement, IconProps>(function PluginIcon(props, ref) {
  const { weight: _weight, size = 24, ...rest } = props;

  return <svg ref={ref} width={size} height={size} aria-hidden="true" viewBox="0 0 24 24" fill="none" stroke="currentColor" {...rest} strokeWidth={1.75} strokeLinecap="round" strokeLinejoin="round" data-backchat-icon="plugin"><path d="M9 6V5a3 3 0 0 1 6 0v1h5v5a3 3 0 1 0 0 6v4H4V6h5Z"/></svg>;
});
export const CloudIcon = forwardRef<SVGSVGElement, IconProps>(function CloudIcon(props, ref) {
  const { weight: _weight, size = 24, ...rest } = props;

  return <svg ref={ref} width={size} height={size} aria-hidden="true" viewBox="0 0 24 24" fill="none" stroke="currentColor" {...rest} strokeWidth={1.75} strokeLinecap="round" strokeLinejoin="round" data-backchat-icon="cloud"><path d="M7 19a4 4 0 0 1-1-8 6 6 0 0 1 12-1 4.5 4.5 0 0 1 0 9H7Z"/></svg>;
});
export const BookIcon = forwardRef<SVGSVGElement, IconProps>(function BookIcon(props, ref) {
  const { weight: _weight, size = 24, ...rest } = props;

  return <svg ref={ref} width={size} height={size} aria-hidden="true" viewBox="0 0 24 24" fill="none" stroke="currentColor" {...rest} strokeWidth={1.75} strokeLinecap="round" strokeLinejoin="round" data-backchat-icon="book"><path d="M12 6C9 4 6 4 3 5v15c3-1 6-1 9 1 3-2 6-2 9-1V5c-3-1-6-1-9 1v15"/></svg>;
});
export const CameraIcon = forwardRef<SVGSVGElement, IconProps>(function CameraIcon(props, ref) {
  const { weight: _weight, size = 24, ...rest } = props;

  return <svg ref={ref} width={size} height={size} aria-hidden="true" viewBox="0 0 24 24" fill="none" stroke="currentColor" {...rest} strokeWidth={1.75} strokeLinecap="round" strokeLinejoin="round" data-backchat-icon="camera"><path d="M8 6l2-3h4l2 3h3a2 2 0 0 1 2 2v11H3V8a2 2 0 0 1 2-2h3Z"/><circle cx="12" cy="12.5" r="3.5"/></svg>;
});
export const MonitorIcon = forwardRef<SVGSVGElement, IconProps>(function MonitorIcon(props, ref) {
  const { weight: _weight, size = 24, ...rest } = props;

  return <svg ref={ref} width={size} height={size} aria-hidden="true" viewBox="0 0 24 24" fill="none" stroke="currentColor" {...rest} strokeWidth={1.75} strokeLinecap="round" strokeLinejoin="round" data-backchat-icon="monitor"><rect x="3" y="4" width="18" height="13" rx="2"/><path d="M12 17v4M8 21h8"/></svg>;
});
export const MoonIcon = forwardRef<SVGSVGElement, IconProps>(function MoonIcon(props, ref) {
  const { weight: _weight, size = 24, ...rest } = props;

  return <svg ref={ref} width={size} height={size} aria-hidden="true" viewBox="0 0 24 24" fill="none" stroke="currentColor" {...rest} strokeWidth={1.75} strokeLinecap="round" strokeLinejoin="round" data-backchat-icon="moon"><path d="M20.2 14.2A8.5 8.5 0 0 1 9.8 3.8a8.5 8.5 0 1 0 10.4 10.4Z"/></svg>;
});
export const MoonStarIcon = forwardRef<SVGSVGElement, IconProps>(function MoonStarIcon(props, ref) {
  const { weight: _weight, size = 24, ...rest } = props;

  return <svg ref={ref} width={size} height={size} aria-hidden="true" viewBox="0 0 24 24" fill="none" stroke="currentColor" {...rest} strokeWidth={1.75} strokeLinecap="round" strokeLinejoin="round" data-backchat-icon="moon-star"><path d="M19.8 14.5A8 8 0 0 1 9.5 4.2a8 8 0 1 0 10.3 10.3Z"/><path d="M18 3v4M16 5h4"/></svg>;
});
export const SunIcon = forwardRef<SVGSVGElement, IconProps>(function SunIcon(props, ref) {
  const { weight: _weight, size = 24, ...rest } = props;

  return <svg ref={ref} width={size} height={size} aria-hidden="true" viewBox="0 0 24 24" fill="none" stroke="currentColor" {...rest} strokeWidth={1.75} strokeLinecap="round" strokeLinejoin="round" data-backchat-icon="sun"><circle cx="12" cy="12" r="4"/><path d="M12 2v2M12 20v2M2 12h2M20 12h2M5 5l1.4 1.4M17.6 17.6 19 19M5 19l1.4-1.4M17.6 6.4 19 5"/></svg>;
});
export const ServerIcon = forwardRef<SVGSVGElement, IconProps>(function ServerIcon(props, ref) {
  const { weight: _weight, size = 24, ...rest } = props;

  return <svg ref={ref} width={size} height={size} aria-hidden="true" viewBox="0 0 24 24" fill="none" stroke="currentColor" {...rest} strokeWidth={1.75} strokeLinecap="round" strokeLinejoin="round" data-backchat-icon="server"><rect x="3" y="4" width="18" height="6" rx="2"/><rect x="3" y="14" width="18" height="6" rx="2"/><circle cx="17" cy="7" r="0.8" fill="currentColor" stroke="none"/><circle cx="17" cy="17" r="0.8" fill="currentColor" stroke="none"/></svg>;
});
export const ReviewOpenIcon = forwardRef<SVGSVGElement, IconProps>(function ReviewOpenIcon(props, ref) {
  const { weight: _weight, size = 24, ...rest } = props;

  return <svg ref={ref} width={size} height={size} aria-hidden="true" viewBox="0 0 24 24" fill="none" stroke="currentColor" {...rest} strokeWidth={1.75} strokeLinecap="round" strokeLinejoin="round" data-backchat-icon="review-open"><circle cx="6" cy="5" r="2"/><circle cx="6" cy="19" r="2"/><path d="M6 7v10"/><circle cx="18" cy="19" r="2"/><path d="M18 17V9a4 4 0 0 0-4-4h-2m3-3-3 3 3 3"/></svg>;
});
export const ReviewMergedIcon = forwardRef<SVGSVGElement, IconProps>(function ReviewMergedIcon(props, ref) {
  const { weight: _weight, size = 24, ...rest } = props;

  return <svg ref={ref} width={size} height={size} aria-hidden="true" viewBox="0 0 24 24" fill="none" stroke="currentColor" {...rest} strokeWidth={1.75} strokeLinecap="round" strokeLinejoin="round" data-backchat-icon="review-merged"><circle cx="6" cy="5" r="2"/><circle cx="6" cy="19" r="2"/><path d="M6 7v10"/><circle cx="18" cy="19" r="2"/><path d="M18 17v-2c0-5-12-3-12-8"/></svg>;
});
export const ReviewClosedIcon = forwardRef<SVGSVGElement, IconProps>(function ReviewClosedIcon(props, ref) {
  const { weight: _weight, size = 24, ...rest } = props;

  return <svg ref={ref} width={size} height={size} aria-hidden="true" viewBox="0 0 24 24" fill="none" stroke="currentColor" {...rest} strokeWidth={1.75} strokeLinecap="round" strokeLinejoin="round" data-backchat-icon="review-closed"><circle cx="6" cy="5" r="2"/><circle cx="6" cy="19" r="2"/><path d="M6 7v10"/><circle cx="18" cy="19" r="2"/><path d="M18 17v-5M15 3l6 6M21 3l-6 6"/></svg>;
});
export const ShieldIcon = forwardRef<SVGSVGElement, IconProps>(function ShieldIcon(props, ref) {
  const { weight: _weight, size = 24, ...rest } = props;

  return <svg ref={ref} width={size} height={size} aria-hidden="true" viewBox="0 0 24 24" fill="none" stroke="currentColor" {...rest} strokeWidth={1.75} strokeLinecap="round" strokeLinejoin="round" data-backchat-icon="shield"><path d="M12 3C9.5 5 7 5.7 4 6v5c0 4.8 3.1 7.7 8 10 4.9-2.3 8-5.2 8-10V6c-3-.3-5.5-1-8-3Z"/></svg>;
});
export const ShieldAskIcon = forwardRef<SVGSVGElement, IconProps>(function ShieldAskIcon(props, ref) {
  const { weight: _weight, size = 24, ...rest } = props;

  return <svg ref={ref} width={size} height={size} aria-hidden="true" viewBox="0 0 24 24" fill="none" stroke="currentColor" {...rest} strokeWidth={1.75} strokeLinecap="round" strokeLinejoin="round" data-backchat-icon="shield-ask"><path d="M12 3C9.5 5 7 5.7 4 6v5c0 4.8 3.1 7.7 8 10 4.9-2.3 8-5.2 8-10V6c-3-.3-5.5-1-8-3Z"/><path d="M12 8v4"/><circle cx="12" cy="15" r="0.8" fill="currentColor" stroke="none"/></svg>;
});
export const ShieldCheckIcon = forwardRef<SVGSVGElement, IconProps>(function ShieldCheckIcon(props, ref) {
  const { weight: _weight, size = 24, ...rest } = props;

  return <svg ref={ref} width={size} height={size} aria-hidden="true" viewBox="0 0 24 24" fill="none" stroke="currentColor" {...rest} strokeWidth={1.75} strokeLinecap="round" strokeLinejoin="round" data-backchat-icon="shield-check"><path d="M12 3C9.5 5 7 5.7 4 6v5c0 4.8 3.1 7.7 8 10 4.9-2.3 8-5.2 8-10V6c-3-.3-5.5-1-8-3Z"/><path d="m8.5 11.5 2.5 2.5 4.5-5"/></svg>;
});
export const ShieldRestrictedIcon = forwardRef<SVGSVGElement, IconProps>(function ShieldRestrictedIcon(props, ref) {
  const { weight: _weight, size = 24, ...rest } = props;

  return <svg ref={ref} width={size} height={size} aria-hidden="true" viewBox="0 0 24 24" fill="none" stroke="currentColor" {...rest} strokeWidth={1.75} strokeLinecap="round" strokeLinejoin="round" data-backchat-icon="shield-restricted"><path d="M12 3C9.5 5 7 5.7 4 6v5c0 4.8 3.1 7.7 8 10 4.9-2.3 8-5.2 8-10V6c-3-.3-5.5-1-8-3Z"/><path d="M9 11.5h6"/></svg>;
});
export const FileIcon = forwardRef<SVGSVGElement, IconProps>(function FileIcon(props, ref) {
  const { weight: _weight, size = 24, ...rest } = props;

  return <svg ref={ref} width={size} height={size} aria-hidden="true" viewBox="0 0 24 24" fill="none" stroke="currentColor" {...rest} strokeWidth={1.75} strokeLinecap="round" strokeLinejoin="round" data-backchat-icon="file"><path d="M13 3H6a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V10a2 2 0 0 0-.586-1.414l-5-5A2 2 0 0 0 13 3Z"/><path d="M13 3v5a2 2 0 0 0 2 2h5"/></svg>;
});
export const FileTextIcon = forwardRef<SVGSVGElement, IconProps>(function FileTextIcon(props, ref) {
  const { weight: _weight, size = 24, ...rest } = props;

  return <svg ref={ref} width={size} height={size} aria-hidden="true" viewBox="0 0 24 24" fill="none" stroke="currentColor" {...rest} strokeWidth={1.75} strokeLinecap="round" strokeLinejoin="round" data-backchat-icon="file-text"><path d="M13 3H6a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V10a2 2 0 0 0-.586-1.414l-5-5A2 2 0 0 0 13 3Z"/><path d="M13 3v5a2 2 0 0 0 2 2h5"/><path d="M8 14h8M8 17h5"/></svg>;
});
export const BrowserIcon = forwardRef<SVGSVGElement, IconProps>(function BrowserIcon(props, ref) {
  const { weight: _weight, size = 24, ...rest } = props;

  return <svg ref={ref} width={size} height={size} aria-hidden="true" viewBox="0 0 24 24" fill="none" stroke="currentColor" {...rest} strokeWidth={1.75} strokeLinecap="round" strokeLinejoin="round" data-backchat-icon="browser"><rect x="3" y="4" width="18" height="16" rx="2"/><path d="M3 9h18"/><circle cx="6" cy="6.5" r="0.6" fill="currentColor" stroke="none"/><circle cx="9" cy="6.5" r="0.6" fill="currentColor" stroke="none"/></svg>;
});
export const PanelLeftIcon = forwardRef<SVGSVGElement, IconProps>(function PanelLeftIcon(props, ref) {
  const { weight: _weight, size = 24, ...rest } = props;

  return <svg ref={ref} width={size} height={size} aria-hidden="true" viewBox="0 0 24 24" fill="none" stroke="currentColor" {...rest} strokeWidth={1.75} strokeLinecap="round" strokeLinejoin="round" data-backchat-icon="panel-left"><rect x="3" y="4" width="18" height="16" rx="2"/><path d="M9 4v16"/></svg>;
});
export const PanelRightIcon = forwardRef<SVGSVGElement, IconProps>(function PanelRightIcon(props, ref) {
  const { weight: _weight, size = 24, ...rest } = props;

  return <svg ref={ref} width={size} height={size} aria-hidden="true" viewBox="0 0 24 24" fill="none" stroke="currentColor" {...rest} strokeWidth={1.75} strokeLinecap="round" strokeLinejoin="round" data-backchat-icon="panel-right"><rect x="3" y="4" width="18" height="16" rx="2"/><path d="M15 4v16"/></svg>;
});
export const PanelTopIcon = forwardRef<SVGSVGElement, IconProps>(function PanelTopIcon(props, ref) {
  const { weight: _weight, size = 24, ...rest } = props;

  return <svg ref={ref} width={size} height={size} aria-hidden="true" viewBox="0 0 24 24" fill="none" stroke="currentColor" {...rest} strokeWidth={1.75} strokeLinecap="round" strokeLinejoin="round" data-backchat-icon="panel-top"><rect x="3" y="4" width="18" height="16" rx="2"/><path d="M3 10h18"/></svg>;
});
export const GlobeIcon = forwardRef<SVGSVGElement, IconProps>(function GlobeIcon(props, ref) {
  const { weight: _weight, size = 24, ...rest } = props;

  return <svg ref={ref} width={size} height={size} aria-hidden="true" viewBox="0 0 24 24" fill="none" stroke="currentColor" {...rest} strokeWidth={1.75} strokeLinecap="round" strokeLinejoin="round" data-backchat-icon="globe"><circle cx="12" cy="12" r="9"/><path d="M3 12h18M12 3c-5 4.5-5 13.5 0 18M12 3c5 4.5 5 13.5 0 18"/></svg>;
});
