import { describe, expect, it } from "vitest";
import { customRepositoryImage, readRepositoryImage } from "./repository-image.js";

const image = "https://repository-images.githubusercontent.com/123/custom.png";
describe("repository custom artwork", () => {
  it("never uses an autogenerated repository card", () => {
    expect(customRepositoryImage({ usesCustomOpenGraphImage: false, openGraphImageUrl: image })).toBeNull();
    expect(customRepositoryImage({ openGraphImageUrl: image })).toBeNull();
    expect(customRepositoryImage({ usesCustomOpenGraphImage: true, openGraphImageUrl: image })).toBe(image);
  });
  it("prefers custom artwork and falls back to the organization or user avatar", () => {
    const avatar = "https://avatars.githubusercontent.com/u/123?s=64";
    const owner = { avatarUrl: avatar };
    expect(customRepositoryImage({ usesCustomOpenGraphImage: true, openGraphImageUrl: image, owner })).toBe(image);
    expect(customRepositoryImage({ usesCustomOpenGraphImage: false, openGraphImageUrl: image, owner })).toBe(avatar);
    expect(customRepositoryImage({ usesCustomOpenGraphImage: true, openGraphImageUrl: "bad-url", owner })).toBe(avatar);
    expect(customRepositoryImage({ owner })).toBe(avatar);
  });
  it("rejects non-image origins and credential-bearing URLs", () => {
    for (const url of ["https://example.com/image.png", "https://githubusercontent.com.evil.test/a", "https://user:pass@repository-images.githubusercontent.com/a", "file:///tmp/a"])
      expect(customRepositoryImage({ usesCustomOpenGraphImage: true, openGraphImageUrl: url })).toBeNull();
  });
  it.each(["git@github.com:team/project.git", "https://github.com/team/project.git"])("resolves %s through authenticated repo metadata", async remote => {
    const result = await readRepositoryImage("/repo", async (cmd, args) => {
      if (cmd === "git") return remote;
      expect(args).toContain("owner=team");
      expect(args).toContain("name=project");
      expect(args.join(" ")).toContain("owner{avatarUrl(size:64)}");
      return JSON.stringify({ data: { repository: { usesCustomOpenGraphImage: true, openGraphImageUrl: image } } });
    });
    expect(result).toBe(image);
  });
  it("falls back for missing CLI or inaccessible private repository", async () => {
    expect(await readRepositoryImage("/repo", async () => { throw new Error("unavailable"); })).toBeNull();
  });
});
