import type { SiteLocale } from "./site";

const en = {
  skip: "Skip to guide",
  homeLabel: "Backchat home",
  navLabel: "Guide navigation",
  language: "中文",
  nav: ["Install", "Sign in", "Existing dsh", "Troubleshooting"],
  breadcrumb: ["Backchat", "Guides", "DeepSeek Harness"],
  kicker: "DEEPSEEK HARNESS + BACKCHAT",
  title: "Use DeepSeek Harness in Backchat.",
  lede: "Install the ACP adapter, sign in without placing an API key in Backchat, and start a DeepSeek session in about ten minutes.",
  meta: ["10 minute setup", "Node.js 22.15+ for manual install", "macOS · Windows · Linux"],
  openBackchat: "Download Backchat",
  viewSource: "View adapter source",
  tocTitle: "On this page",
  fastKicker: "RECOMMENDED PATH",
  fastTitle: "Let Backchat manage the adapter.",
  fastIntro: "Backchat ships a registry entry for DeepSeek Harness. You do not need to edit JSON or add a custom command for the standard setup.",
  fastSteps: [
    ["Open agent settings", "Launch Backchat, open Settings → Agents, then find DeepSeek Harness at the top of Registry."],
    ["Install the adapter", "Choose Install. Backchat installs @openma/deepseek-harness-acp into its managed ACP tools directory and enables it."],
    ["Save an API key", "Choose Sign in, then pick API Key, Custom model gateway, or Browser. API key and gateway send `_meta` through ACP authenticate; Browser opens a local page. Backchat does not keep the secret."],
    ["Start a real session", "Create a new chat, choose a project and DeepSeek Harness, then use /status to verify the active model, mode, and credential state."],
  ],
  managedNote: "Your API key stays in DeepSeek Harness's own credential store. Backchat launches the adapter but does not copy the key into its settings.",
  manualKicker: "MANUAL INSTALL",
  manualTitle: "Prefer your own global command?",
  manualBody: "Use this path when you want dsh-acp available outside Backchat. The package requires Node.js 22.15 or newer. After installing, return to Settings → Agents and choose Refresh.",
  commandLabel: "Terminal",
  authKicker: "AUTHENTICATION",
  authTitle: "One credential store, three safe entry points.",
  authBody: "dsh-acp reuses $DSH_HOME/.credentials.yaml—the same mode-600 file used by the dsh Web UI. In Backchat, choose API Key, Custom model gateway, or Browser. You can also save a key with dsh-acp login or in dsh web under Settings → Models.",
  authFallback: "For ephemeral environments, DEEPSEEK_API_KEY and optional DEEPSEEK_BASE_URL can be passed to the process. Do not commit either value or place it in a public command example.",
  profileKicker: "EXISTING DSH USERS",
  profileTitle: "Attach the ACP bridge to a dsh profile.",
  profileBody: "If your models, presets, skills, and settings already live in dsh, install the adapter as a profile plugin and point a Backchat custom agent at that profile.",
  customAgentTitle: "Then add a custom agent in Settings → Agents",
  customFields: [["ID", "deepseek-profile"], ["Name", "DeepSeek Harness (profile)"], ["Command", "dsh"], ["Arguments", "--profile acp"]],
  verifyKicker: "VERIFY THE CONNECTION",
  verifyTitle: "What should work after setup",
  features: ["Streaming responses and reasoning", "Tool calls with file diffs and terminal output", "Read-only, workspace-write, and danger-full-access modes", "Live model and reasoning-effort choices", "Slash commands, skills, sessions, plans, usage, and MCP servers"],
  permissionNote: "Sessions start in workspace-write. Use danger-full-access only in disposable checkouts or containers.",
  troubleKicker: "TROUBLESHOOTING",
  troubleTitle: "Four checks solve most setup failures.",
  trouble: [
    ["DeepSeek Harness is not listed", "Open Settings → Agents and choose Refresh. For manual installs, confirm dsh-acp is on PATH with dsh-acp --help."],
    ["Install reports an unsupported Node version", "Run node --version. The current adapter package requires Node.js 22.15 or newer."],
    ["The row says Auth needed", "Open Sign in, save an API key, or run dsh-acp login. Then start a new session."],
    ["A dsh profile does not load", "Run dsh --profile acp once in a terminal, then verify the custom Backchat command is dsh with arguments --profile acp and that both processes share DSH_HOME."],
  ],
  repoHelp: "Open an adapter issue",
  ctaTitle: "Ready to start a DeepSeek session?",
  ctaBody: "Install Backchat, open Settings → Agents, and follow the managed path above.",
  backHome: "Back to Backchat",
  footer: "Official Backchat guide for DeepSeek Harness via Agent Client Protocol.",
};

const zh: typeof en = {
  skip: "跳到教程正文",
  homeLabel: "Backchat 首页",
  navLabel: "教程导航",
  language: "EN",
  nav: ["安装", "登录", "现有 dsh", "故障排查"],
  breadcrumb: ["Backchat", "教程", "DeepSeek Harness"],
  kicker: "DEEPSEEK HARNESS + BACKCHAT",
  title: "在 Backchat 中使用 DeepSeek Harness。",
  lede: "安装 ACP 适配器，不把 API Key 写进 Backchat，并在大约十分钟内开始一段 DeepSeek 会话。",
  meta: ["约 10 分钟", "手动安装需 Node.js 22.15+", "macOS · Windows · Linux"],
  openBackchat: "下载 Backchat",
  viewSource: "查看适配器源码",
  tocTitle: "本页内容",
  fastKicker: "推荐方式",
  fastTitle: "让 Backchat 管理适配器。",
  fastIntro: "Backchat 已内置 DeepSeek Harness 注册项。标准配置不需要编辑 JSON，也不需要手工添加命令。",
  fastSteps: [
    ["打开智能体设置", "启动 Backchat，进入“设置 → 智能体”，在 Registry 顶部找到 DeepSeek Harness。"],
    ["安装适配器", "点击“安装”。Backchat 会把 @openma/deepseek-harness-acp 安装到托管的 ACP 工具目录并自动启用。"],
    ["保存 API Key", "点击“登录”，再选 API Key、自定义网关或浏览器。前两项通过 ACP authenticate 的 `_meta` 提交；浏览器打开本地页。Backchat 不保存密钥。"],
    ["开始真实会话", "新建对话，选择项目与 DeepSeek Harness，然后执行 /status，检查当前模型、权限模式和登录状态。"],
  ],
  managedNote: "API Key 保存在 DeepSeek Harness 自己的凭据存储中。Backchat 只负责启动适配器，不会把密钥复制进应用设置。",
  manualKicker: "手动安装",
  manualTitle: "希望全局使用 dsh-acp？",
  manualBody: "当你希望在 Backchat 之外也能调用 dsh-acp 时使用这条路径。当前包要求 Node.js 22.15 或更高版本。安装后返回“设置 → 智能体”并点击“刷新”。",
  commandLabel: "终端",
  authKicker: "身份验证",
  authTitle: "一个凭据存储，三种安全入口。",
  authBody: "dsh-acp 复用 $DSH_HOME/.credentials.yaml，也就是 dsh Web UI 使用的 mode-600 文件。在 Backchat 里可选 API Key、自定义网关或浏览器。也可以用 dsh-acp login，或在 dsh web 的“设置 → 模型”保存密钥。",
  authFallback: "临时环境可通过进程变量传入 DEEPSEEK_API_KEY 和可选的 DEEPSEEK_BASE_URL。不要提交这些值，也不要把它们写进公开命令示例。",
  profileKicker: "已有 DSH 的用户",
  profileTitle: "把 ACP bridge 接入 dsh profile。",
  profileBody: "如果模型、预设、技能和设置已经放在 dsh 中，可将适配器安装为 profile 插件，再让 Backchat 的自定义智能体指向这个 profile。",
  customAgentTitle: "然后在“设置 → 智能体”中添加自定义智能体",
  customFields: [["ID", "deepseek-profile"], ["名称", "DeepSeek Harness (profile)"], ["命令", "dsh"], ["参数", "--profile acp"]],
  verifyKicker: "验证连接",
  verifyTitle: "配置完成后应具备的能力",
  features: ["流式回答与思考过程", "带文件差异和终端输出的工具调用", "只读、工作区写入和完全访问权限模式", "实时模型与推理强度选择", "斜杠命令、技能、会话、计划、用量和 MCP 服务"],
  permissionNote: "会话默认使用 workspace-write。danger-full-access 只应在一次性检出目录或容器中使用。",
  troubleKicker: "故障排查",
  troubleTitle: "多数配置问题都能用四项检查解决。",
  trouble: [
    ["列表中没有 DeepSeek Harness", "打开“设置 → 智能体”并点击“刷新”。手动安装时，可运行 dsh-acp --help 检查命令是否在 PATH 中。"],
    ["安装提示 Node 版本不支持", "运行 node --version。当前适配器包要求 Node.js 22.15 或更高版本。"],
    ["列表显示需要登录", "打开“登录”并保存 API Key，或运行 dsh-acp login。然后新建会话。"],
    ["dsh profile 无法加载", "先在终端运行一次 dsh --profile acp，再确认 Backchat 自定义命令是 dsh、参数是 --profile acp，并确保两个进程共用 DSH_HOME。"],
  ],
  repoHelp: "提交适配器问题",
  ctaTitle: "准备开始 DeepSeek 会话了吗？",
  ctaBody: "安装 Backchat，进入“设置 → 智能体”，按照上面的推荐路径完成配置。",
  backHome: "返回 Backchat",
  footer: "Backchat 通过 Agent Client Protocol 使用 DeepSeek Harness 的官方教程。",
};

export const deepSeekCopy: Record<SiteLocale, typeof en> = { en, "zh-CN": zh };
