import type { SiteLocale } from "./site";

const en = {
  skip: "Skip to content",
  homeLabel: "Backchat home",
  navLabel: "Primary navigation",
  nav: { product: "Product", agents: "Agents", download: "Download", language: "中文" },
  announcementBadge: "New",
  announcement: "DeepSeek Harness setup guide",
  eyebrow: "MULTI-HARNESS · ACP-NATIVE",
  heroTitle: "One workspace. Every agent.",
  heroTitleLines: ["One workspace.", "Every agent."],
  heroLede: "Run Claude Code, Codex, DeepSeek Harness, and other ACP agents in one desktop. Bring multiple agents into the same conversation, use the built-in browser, and open MCP Apps or Codex plugins right beside the chat.",
  downloadMac: "Download for macOS",
  viewGithub: "View on GitHub",
  heroMeta: ["Apple Silicon preview", "v0.0.3", "Open source"],
  heroPreviewLabel: "Backchat desktop preview",
  heroImageAlt: "Backchat desktop home",
  heroCaption: "Pick a project, pick a harness, and start with the agent's real capabilities.",
  agentCloud: "A shared desktop for the agents you already use",
  productKicker: "THE PRODUCT",
  productTitle: "The conversation stays central. The tools stay close.",
  productLede: "Backchat is a desktop client, not another agent dashboard. Multi-agent chats, files, terminals, the built-in browser, MCP Apps, and Codex plugins appear when the work needs them.",
  storyOneTitle: "See the work, not a wall of logs.",
  storyOneBody: "Thinking and tool calls fold into a readable activity history. Follow the current action while it runs; open the details only when you need them.",
  storyOneChecks: ["Grouped tool activity", "Streaming thoughts", "Stable conversation timeline"],
  storyOneAlt: "Grouped agent activity in Backchat",
  storyTwoTitle: "Outputs have somewhere to live.",
  storyTwoBody: "Keep project files, a terminal, and the built-in browser beside the conversation. Add multiple agents to one chat, or open native MCP Apps and Codex plugins without leaving the task.",
  capabilitiesLabel: "Workspace capabilities",
  capabilities: ["Multi-agent chat", "Built-in browser", "Project files", "Terminal", "Native MCP Apps", "Codex plugins"],
  storyTwoAlt: "Interactive output shown beside a Backchat conversation",
  truthKicker: "LIVE TRUTH",
  truthTitle: "Agent-aware, not vendor-shaped.",
  truthBody: "Models, commands, modes, permissions, and session controls come from the selected harness. Backchat does not invent a generic capability layer and pretend every agent works the same way.",
  truthLabel: "Example live harness capabilities",
  agentsKicker: "YOUR HARNESS, YOUR CHOICE",
  agentsTitle: "Bring the agent. Keep its strengths.",
  agentsBody: "Backchat discovers or installs ACP-compatible harnesses from Settings, then keeps their setup separate from the conversation itself.",
  agentsTableLabel: "Supported agents",
  columns: ["Agent", "ACP entry", "Connection"],
  agentDetails: ["Official ACP adapter", "Native Codex workflow", "Standalone or dsh profile", "Gemini ACP mode", "OpenCode ACP mode", "Hermes ACP entry", "OpenClaw ACP entry"],
  nativeKicker: "NATIVE SUPPORT",
  nativeTitle: "Native support for MCP Apps and Codex plugins.",
  nativeBody: "Interactive apps and plugin output open inside the task, alongside the conversation, files, browser, and terminal—not in a detached dashboard.",
  nativeItemsLabel: "Native extension support",
  nativeItems: ["Interactive MCP Apps", "Codex plugins"],
  downloadKicker: "DESKTOP PREVIEW",
  downloadTitle: "Bring your agents into one quiet room.",
  downloadBody: "Backchat is pre-release and under active development. Download the current macOS build, or package a native Windows or Linux build on your own machine.",
  downloadLatest: "Download latest build",
  buildSource: "Build from source",
  runbookKicker: "WINDOWS + LINUX",
  runbookTitle: "Package Backchat where you will run it.",
  runbookBody: "Choose the recipe for your operating system. Each one builds Backchat from source and creates a native, unsigned installer on that machine.",
  prepare: "Prepare",
  build: "Build",
  collect: "Collect",
  buildInstruction: "Run the complete command block below.",
  windowsRequirements: "Windows 10/11 · Git · Node.js 20+",
  linuxRequirements: "64-bit Linux · Git · Node.js 20+",
  runbookNote: "Package on the target operating system. If a native dependency falls back to compilation, install that platform's standard C/C++ build tools and retry.",
  footer: "One desktop for ACP agents, tools, and outputs.",
  deepSeekGuide: "DeepSeek guide",
};

const zh: typeof en = {
  skip: "跳到主要内容",
  homeLabel: "Backchat 首页",
  navLabel: "主导航",
  nav: { product: "产品", agents: "智能体", download: "下载", language: "EN" },
  announcementBadge: "新",
  announcement: "DeepSeek Harness 配置教程",
  eyebrow: "多 HARNESS · 原生 ACP",
  heroTitle: "一个工作区，连接所有智能体。",
  heroTitleLines: ["一个工作区，", "连接所有智能体。"],
  heroLede: "在一个桌面中运行 Claude Code、Codex、DeepSeek Harness 等 ACP 智能体。让多个 Agent 加入同一段对话，直接使用内置浏览器，并在对话旁原生打开 MCP App 或 Codex Plugin。",
  downloadMac: "下载 macOS 版",
  viewGithub: "在 GitHub 查看",
  heroMeta: ["Apple Silicon 预览版", "v0.0.3", "开源"],
  heroPreviewLabel: "Backchat 桌面预览",
  heroImageAlt: "Backchat 桌面首页",
  heroCaption: "选择项目和 Harness，然后使用智能体真正具备的能力开始工作。",
  agentCloud: "你常用的智能体，共用一个桌面工作区",
  productKicker: "产品",
  productTitle: "对话始终居中，工具随用随开。",
  productLede: "Backchat 是桌面客户端，不是又一个智能体仪表盘。多 Agent 对话、文件、终端、内置浏览器、MCP App 和 Codex Plugin 只在任务需要时出现。",
  storyOneTitle: "看清工作进展，而不是淹没在日志里。",
  storyOneBody: "思考过程和工具调用会折叠成清晰的活动历史。运行时跟随当前动作，需要时再展开细节。",
  storyOneChecks: ["归组的工具活动", "流式思考过程", "稳定的对话时间线"],
  storyOneAlt: "Backchat 中归组展示的智能体活动",
  storyTwoTitle: "每种输出都有合适的位置。",
  storyTwoBody: "让项目文件、终端和内置浏览器留在对话旁。把多个 Agent 加入同一段对话，或原生打开 MCP App 与 Codex Plugin，全程无需离开任务。",
  capabilitiesLabel: "工作区能力",
  capabilities: ["多 Agent 对话", "内置浏览器", "项目文件", "终端", "原生 MCP App", "Codex Plugin"],
  storyTwoAlt: "Backchat 对话旁显示的交互式输出",
  truthKicker: "实时真相",
  truthTitle: "理解智能体，而不是强行统一。",
  truthBody: "模型、命令、模式、权限和会话控制都来自当前 Harness。Backchat 不会编造一套通用能力，再假装所有智能体都一样。",
  truthLabel: "Harness 实时能力示例",
  agentsKicker: "选择你的 HARNESS",
  agentsTitle: "带上智能体，保留它的长处。",
  agentsBody: "Backchat 可在设置中发现或安装 ACP 兼容 Harness，并将配置过程与对话本身分离。",
  agentsTableLabel: "支持的智能体",
  columns: ["智能体", "ACP 入口", "连接方式"],
  agentDetails: ["官方 ACP 适配器", "原生 Codex 工作流", "独立服务或 dsh profile", "Gemini ACP 模式", "OpenCode ACP 模式", "Hermes ACP 入口", "OpenClaw ACP 入口"],
  nativeKicker: "原生支持",
  nativeTitle: "原生支持 MCP App 与 Codex Plugin。",
  nativeBody: "交互式应用和插件输出直接在任务中打开，与对话、文件、浏览器和终端并列，而不是被压成一段普通文本。",
  nativeItemsLabel: "原生扩展支持",
  nativeItems: ["交互式 MCP App", "Codex Plugin"],
  downloadKicker: "桌面预览版",
  downloadTitle: "让所有智能体进入同一个安静空间。",
  downloadBody: "Backchat 仍处于预发布阶段。你可以直接下载 macOS 版本，也可以在自己的 Windows 或 Linux 电脑上打包原生版本。",
  downloadLatest: "下载最新版本",
  buildSource: "从源码构建",
  runbookKicker: "WINDOWS + LINUX",
  runbookTitle: "在目标系统上打包 Backchat。",
  runbookBody: "选择对应操作系统的步骤。每套流程都会从源码构建，并在本机生成未签名的原生安装包。",
  prepare: "准备",
  build: "构建",
  collect: "获取产物",
  buildInstruction: "在终端中完整执行下面的命令。",
  windowsRequirements: "Windows 10/11 · Git · Node.js 20+",
  linuxRequirements: "64 位 Linux · Git · Node.js 20+",
  runbookNote: "请在目标操作系统上打包。如果原生依赖需要源码编译，请安装该平台的标准 C/C++ 构建工具后重试。",
  footer: "把 ACP 智能体、工具和输出放在同一个桌面中。",
  deepSeekGuide: "DeepSeek 教程",
};

export const homepageCopy: Record<SiteLocale, typeof en> = { en, "zh-CN": zh };
